version: "3.9"
services:
  americano-mysql:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
  americano- =redis:
    image: redis:latest
    ports:
      - '6379:6379'

# docker compose --build -up
