FROM adoptopenjdk/openjdk11

VOLUME /tmp

ARG JAR_FILE=build/libs/*.jar

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java",  "-jar", "-Dspring.profiles.active=prod-v1", "-Duser.timezone=Asia/Seoul","/app.jar"]